services:
  mongodb:
    image: mongo:7.0  # Versión estable reciente
    container_name: barber-flow-mongodb-dev
    restart: always
    ports:
      - "27017:27017"  # Expone MongoDB en localhost:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: barberflow_2026
      MONGO_INITDB_DATABASE: barber-flow-dev-db
    volumes:
      - mongodb_data:/data/db  # Persiste los datos
      - ./mongo-init:/docker-entrypoint-initdb.d  # Scripts iniciales opcionales
    networks:
      - backend-network

volumes:
  mongodb_data:
    driver: local

networks:
  backend-network:
    driver: bridge