export const en = {
  common: {
    active: "Active",
    call: "Call",
    cancel: "Cancel",
    close: "Close",
    create: "Create",
    delete: "Delete",
    dismiss: "Dismiss",
    inactive: "Inactive",
    markAllAsRead: "Mark all as read",
    message: "Message",
    ok: "OK",
    open: "Open",
    refresh: "Refresh",
    reset: "Reset",
    save: "Save",
    search: "Search",
    select: "Select",
    today: "Today",
    update: "Update",
    visible: "Visible",
    unread: "Unread",
    somethingWentWrong: "Something went wrong.",
  },
  drawer: {
    cancel: "Cancel",
    help: "Help",
    helpDescription: "Get help and usage guidance",
    helpMessage: "For help, contact support or check the documentation.",
    helpTitle: "Help",
    heroBody:
      "Use the drawer to reach settings, support, and account-level actions from one clean workspace surface.",
    logout: "Sign out",
    logoutDescription: "Close the current session on this device",
    logoutMessage: "Are you sure you want to sign out?",
    logoutTitle: "Sign out",
    noAccountMetadata: "No account metadata available",
    settings: "Settings",
    settingsDescription: "Theme, language, notifications, and app preferences",
    studioAccess: "Studio access",
    support: "Support",
    workspace: "Workspace",
  },
  header: {
    guest: "Guest",
    openMenu: "Open menu",
    openNotifications: "Open notifications",
    signedInAs: "Signed in as %{identity}",
    workspace: "Workspace",
  },
  login: {
    appointments: "Appointments",
    authFailed: "Authentication failed",
    enterPassword: "Enter your password",
    enterUsername: "Enter your username",
    helperText: "Your session is stored securely on this device after a successful login.",
    heroBody:
      "Sign in to access appointments, client records, notifications, and operational settings from one professional workspace.",
    heroTitle: "Manage your barber workspace with confidence.",
    notifications: "Notifications",
    password: "Password",
    secureAccess: "Secure access",
    signIn: "Sign in",
    signInToContinue: "Sign in to continue",
    subtitle: "Use your assigned username and password to open the mobile workspace.",
    username: "Username",
    validation: "Please provide both username and password.",
    welcomeBack: "Welcome back",
    clients: "Clients",
  },
  navigation: {
    alerts: "Alerts",
    calendar: "Schedule",
    clients: "Clients",
    dailyReport: "Closeout",
    home: "Home",
    settings: "Settings",
  },
  settings: {
    about: "About",
    aboutSubtitle:
      "Application information and development credits presented with the same polished card treatment as the rest of the settings workspace.",
    developer: "Developer",
    dailyReportCalculations: "Daily Report Calculations",
    followSystem: "Follow system",
    manageApplicationUsers: "Manage Application Users",
    preferences: "Preferences",
    quickToggle: "Quick toggle",
    title: "Settings",
    version: "Version",
    workspaceSettings: "Workspace settings",
    settingsAndPreferences: "Settings & Preferences",
    heroSubtitle:
      "Configure application preferences, manage admin-only application users, and keep the experience aligned with your workflow.",
    preferencesPanel: {
      darkModeBody:
        "Choose a manual theme or let the app follow system preferences across the full experience.",
      darkModeTitle: "Dark Mode",
      followDeviceLanguage: "Use device language",
      languageManualBody: "Choose the language you want to keep in the app.",
      languageSystemBody:
        "The app follows your device language. Current language: %{language}.",
      languageTitle: "Application language",
      notifications: "Notifications (%{count})",
      system: "System",
      light: "Light",
      dark: "Dark",
      english: "English",
      spanish: "Spanish",
    },
    alerts: {
      applicationUserCreated: "Application user %{id} created successfully.",
      applicationUserDeleted: "Application user %{id} removed successfully.",
      applicationUserUpdated: "Application user %{id} updated successfully.",
      confirmDeleteUser: "Remove %{id}?",
      dailyReportReset: "Daily report calculations were reset to defaults.",
      dailyReportSaved: "Daily report calculations updated successfully.",
      deleteFailed: "Delete failed",
      noApplicationUserSelected: "No application user selected.",
      noApplicationUserSearchResult: "No application user found for that search.",
      reportValidation: "Please review the daily report calculation values.",
      saveFailed: "Save failed",
      searchFailed: "Search failed",
      searchHint: "Enter a Barber ID, email, or phone to search.",
      validation: "Please fix the required fields.",
    },
    manageUsersForm: {
      address: "Address",
      barberId: "Barber ID",
      barberName: "Barber name *",
      barberPhone: "Barber phone *",
      createSubtitle:
        "Use the generated barber ID and complete the required fields to create a new application user.",
      createUser: "Create user",
      editSubtitle:
        "You are editing an existing application user and barber profile.",
      email: "Email *",
      eyebrow: "Admin tools",
      name: "Name *",
      phone: "Phone *",
      searchLabel: "Search by Barber ID, email, or phone",
      subtitle:
        "Create, search, update, and remove application users with barber profile data prepared for the backend.",
      title: "Manage Application Users",
      updateUser: "Update user",
      userDataTitle: "Application user data",
    },
    reportCalculationForm: {
      commissionPercentage: "Barber commission percentage",
      fixedDailyExpense: "Fixed daily expense",
      subtitle:
        "Net profit is calculated as gross revenue minus barber commission and fixed daily expense.",
      title: "Daily closeout formula",
    },
  },
  validation: {
    appointmentClientNameRequired: "Client name is required.",
    appointmentPaymentMethodRequired: "Select a payment method.",
    appointmentServicePricePositive: "Price must be greater than 0.",
    appointmentServicePriceRequired: "Service price is required.",
    appointmentTimeRequired: "Time is required.",
    barberNameRequired: "Barber name is required.",
    barberPhoneFormat: "Barber phone must be 0000-0000.",
    barberPhoneRequired: "Barber phone is required.",
    commissionPercentageRange: "Commission percentage must be between 0 and 100.",
    emailRequired: "Email is required.",
    fixedDailyExpenseRange: "Fixed daily expense must be 0 or greater.",
    invalidEmail: "Invalid email address.",
    lastNameRequired: "Last name is required.",
    nameRequired: "Name is required.",
    phoneFormat: "Phone must be 0000-0000.",
    phoneRequired: "Phone is required.",
    required: "Required.",
  },
  appointments: {
    paymentMethods: {
      card: "Credit/Debit Card",
      cash: "Cash",
      sinpeMovil: "Sinpe Movil",
      transfer: "Digital Transfer",
    },
  },
  clients: {
    alerts: {
      clientCreated: "Client created.",
      clientRemoved: "Client removed successfully.",
      clientUpdated: "Client updated.",
      listLoadFailed: "Clients could not be loaded.",
      noClientSelected: "No client selected to remove.",
      removeClientMessage: "Remove client?",
      removeFailed: "Remove failed",
      saveFailed: "Save failed",
      searchFailed: "Search failed",
      validation: "Please fix the required fields.",
    },
    buttons: {
      createClient: "Create client",
      delete: "Delete",
      findClient: "Find client",
      newClient: "New client",
      scheduleAppointment: "Schedule appointment",
      scheduleAppointmentA11y: "Schedule appointment for %{clientName}",
      resetForm: "Reset form",
      saveChanges: "Save changes",
    },
    list: {
      emptyBody: "Create your first client or refine your search to see matching records here.",
      emptyTitle: "No clients to show",
      helper: "Tap any client to update the information already registered in the system.",
      listTitle: "Client directory",
      noEmail: "No email registered",
      searchPlaceholder: "Search by name, phone, or email",
      subtitle: "Review clients, open a record to edit it, or create a new one from the floating action menu.",
      title: "Clients workspace",
    },
    form: {
      activeDescription: "Use this to show whether the client profile is currently active.",
      activeTitle: "Client active",
      address: "Address",
      birthday: "Birthday",
      createEyebrow: "Create client",
      createScreenTitle: "Create client",
      createTitleFallback: "New client",
      createSubtitle: "Add contact details and preferences to save this client.",
      editEyebrow: "Client profile",
      editScreenTitle: "Edit client",
      editingExisting: "Editing existing client",
      email: "Email",
      firstName: "First name *",
      identitySubtitle: "Required information to create or update a client profile.",
      identityTitle: "Identity",
      lastName: "Last name *",
      paymentMethod: "Payment method",
      phone: "Phone *",
      preferences: "Preferences",
      preferencesSubtitle: "Set payment preferences and active status.",
      preferencesTitle: "Preferences",
      profileDetailsSubtitle: "Optional information that helps personalize the experience.",
      profileDetailsTitle: "Profile details",
      selectDate: "Select date",
      statusActive: "Active",
      statusInactive: "Inactive",
    },
    paymentMethods: {
      cash: "Cash",
      none: "None",
      sinpeMovil: "Quick Transfer (Sinpe)",
      transfer: "Bank Transfer",
    },
    screen: {
      existingClientBody:
        "Update contact details, preferences, and account status for the selected client.",
      heroEyebrow: "Client workspace",
      newClientBody:
        "Create a polished client profile with contact details, preferences, and account status.",
      noClientSelectedTitle: "Client management",
      title: "Clients",
    },
    searchModal: {
      emptyBody:
        "Use the search field to find existing clients without loading the full directory.",
      emptyTitle: "No clients found",
      eyebrow: "Find client",
      message: "Message",
      placeholder: "Search clients",
      select: "Select",
      subtitle: "Search by name, phone, or any available client detail.",
      title: "Search saved clients",
    },
  },
  dailyReport: {
    attendanceEyebrow: "Attendance",
    attendanceSubtitle: "Detailed ledger of the completed clients counted in this closure.",
    attendanceTitle: "Completed appointments",
    changeDay: "Change day",
    collectionsEyebrow: "Collections",
    collectionsSubtitle:
      "Review how the day's completed sales were paid to reconcile the cash drawer and digital collections.",
    collectionsTitle: "Payment method breakdown",
    commission: "Commission",
    commissionAmount: "Commission amount",
    completedAppointmentMeta_one: "%{count} completed appointment",
    completedAppointmentMeta_other: "%{count} completed appointments",
    dailyExpense: "Daily expense",
    dailyExpenseBreakdown: "Fixed daily expense",
    formulaEyebrow: "Profit formula",
    formulaSubtitle: "Net profit = gross revenue - barber commission - fixed daily expense",
    formulaTitle: "Daily earnings",
    generalService: "General service",
    heroEyebrow: "Shop owner summary",
    heroSubtitle:
      "Track completed services, collected sales, and actual daily profit from one operational report.",
    heroTitle: "Daily closure report",
    metrics: {
      customersServed: "Customers served",
      grossRevenue: "Gross revenue",
      netProfit: "Net profit",
    },
    noCompletedAppointments: "No completed appointments",
    noCompletedAppointmentsBody:
      "Mark appointments as completed in Calendar to include them in the daily closure report.",
    paymentMethodNotSet: "Payment method not set",
    selectedDay: "Selected day",
    title: "Daily Closure",
  },
  calendar: {
    agendaDay: "Day agenda",
    appointmentCountForDay_one: "%{count} appointment for this day",
    appointmentCountForDay_other: "%{count} appointments for this day",
    emptyBodyDay: "No appointments have been booked for this day yet.",
    emptyBodyMonth:
      "Select a day in the calendar to view appointments or long-press it to create a new booking.",
    emptyBodyWeek: "Select a day of the week and use Schedule to create an appointment.",
    emptyTitle: "No appointments",
    hint: "Tap a day to view appointments. Long press to create a new appointment.",
    monthView: "Month view",
    newAppointment: "New appointment",
    schedule: "Schedule",
    selectedDate: "Selected date",
    title: "Calendar",
    today: "Today",
    viewDay: "Day view",
    viewWeek: "Week view",
    weekOf: "Week of %{date}",
    weekSummary_one: "%{count} appointment",
    weekSummary_other: "%{count} appointments",
    appointmentModal: {
      cancel: "Cancel",
      clientName: "Client name",
      completedInfo: "Completed appointments will appear in the daily report.",
      dateSelected: "Selected date: %{date}",
      editTitle: "Edit booking",
      eyebrow: "New appointment",
      notes: "Notes",
      notesPlaceholder: "Instructions, preferences, or reminders",
      paymentMethod: "Payment method",
      paymentMethodPlaceholder: "Select how this appointment was charged",
      phone: "Phone",
      saveAppointment: "Save appointment",
      saveChanges: "Save changes",
      service: "Service",
      servicePlaceholder: "Classic haircut, beard trim, combo...",
      servicePrice: "Service price",
      status: "Appointment status",
      statuses: {
        cancelled: "Cancelled",
        completed: "Completed",
        confirmed: "Confirmed",
        scheduled: "Scheduled",
      },
      time: "Time",
      title: "Schedule appointment",
    },
  },
  notifications: {
    alerts: {
      refreshFailed: "Notifications could not be refreshed.",
      refreshFailedTitle: "Refresh failed",
    },
    delayedClientsDescription:
      "Clients who have not visited recently and do not have a future appointment.",
    delayedClientsEmptyBody:
      "Delayed-client reminders will appear here once a client crosses the current follow-up threshold.",
    delayedClientMessage: "%{name} has not visited in %{days} days.",
    delayedClientsEmptyTitle: "No delayed clients",
    delayedClientsTitle: "Needs Attention",
    disabledBody: "Enable notifications in Settings to restore the summary feed and unread badge counts.",
    disabledTitle: "Notifications are disabled",
    heroEyebrow: "Daily summary",
    heroSubtitle:
      "Review tomorrow's agenda, identify clients that need follow-up, and keep notification noise reduced to actionable summaries.",
    heroTitle: "Notifications workspace",
    metaNeedsFollowUp: "Needs follow-up",
    metaTomorrow: "Tomorrow",
    tomorrowDescription: "One summary notification for tomorrow's scheduled appointments.",
    tomorrowEmptyBody:
      "When appointments exist for tomorrow, the app will group them into a single daily agenda summary.",
    tomorrowEmptyTitle: "No summary for tomorrow",
    tomorrowMessageOne: "You have 1 appointment scheduled for tomorrow with %{name}.",
    tomorrowMessageOther: "You have %{count} appointments scheduled for tomorrow.",
    tomorrowTitle: "Tomorrow",
    title: "Notifications",
  },
  contactActions: {
    callUnavailableMessage: "This client does not have a valid phone number.",
    callUnavailableOpen: "Your device could not open the phone dialer.",
    callUnavailableTitle: "Call unavailable",
    chooseContactMethod: "Choose how to contact this client.",
    sendMessage: "Send message",
    smsUnavailableMessage: "This client does not have a valid phone number.",
    smsUnavailableOpen: "Your device could not open the SMS app.",
    smsUnavailableTitle: "SMS unavailable",
    whatsappUnavailableMessage: "This client does not have a valid phone number.",
    whatsappUnavailableOpen:
      "WhatsApp is not installed or could not be opened on this device.",
    whatsappUnavailableTitle: "WhatsApp unavailable",
    hello: "Hello",
    helloName: "Hello %{name}",
  },
} as const;