	export const en = {
	common: {
		active: "Active",
		call: "Call",
		cancel: "Cancel",
		close: "Close",
		create: "Create",
		delete: "Delete",
		dismiss: "Dismiss",
		inactive: "Inactive",
		markAllAsRead: "Mark all as read",
		message: "Message",
		ok: "OK",
		open: "Open",
		refresh: "Refresh",
		reset: "Reset",
		save: "Save",
		search: "Search",
		select: "Select",
		today: "Today",
		update: "Update",
		visible: "Visible",
		unread: "Unread",
		somethingWentWrong: "Something went wrong.",
	},
	drawer: {
		cancel: "Cancel",
		deleteAccount: "Delete My Account",
		deleteAccountConfirm: "Delete",
		deleteAccountDescription: "Permanently delete your account and data",
		deleteAccountMessage: "This action is permanent and irreversible. All your data will be deleted.",
		deleteAccountTitle: "Delete Account",
		help: "Help",
		helpDescription: "Get help and usage guidance",
		helpMessage: "For help, contact support or check the documentation.",
		helpTitle: "Help",
		heroBody:
		"Use the drawer to reach settings, support, and account-level actions from one clean workspace surface.",
		logout: "Sign out",
		logoutDescription: "Close the current session on this device",
		logoutMessage: "Are you sure you want to sign out?",
		logoutTitle: "Sign out",
		noAccountMetadata: "No account metadata available",
		settings: "Settings",
		settingsDescription: "Theme, language, notifications, and app preferences",
		studioAccess: "Studio access",
		support: "Support",
		workspace: "Workspace",
	},
	header: {
		guest: "Guest",
		openMenu: "Open menu",
		openNotifications: "Open notifications",
		signedInAs: "Signed in as %{identity}",
		workspace: "Workspace",
	},
	login: {
		appointments: "Appointments",
		authFailed: "Authentication failed",
		enterPassword: "Enter your password",
		enterUsername: "Enter your username",
		helperText: "Your session is stored securely on this device after a successful login.",
		heroBody:
		"Sign in to access appointments, client records, notifications, and operational settings from one professional workspace.",
		heroTitle: "Manage your barber workspace with confidence.",
		notifications: "Notifications",
		password: "Password",
		secureAccess: "Secure access",
		signIn: "Sign in",
		signInToContinue: "Sign in to continue",
		subtitle: "Use your assigned username and password to open the mobile workspace.",
		username: "Username",
		validation: "Please provide both username and password.",
		welcomeBack: "Welcome back",
		clients: "Clients",
	},
	navigation: {
		alerts: "Alerts",
		barberShops: "Barber Shops",
		calendar: "Schedule",
		clients: "Clients",
		dailyReport: "Closeout",
		home: "Home",
		settings: "Settings",
	},
	avatarPicker: {
		cameraPermissionRequired:
			"Camera permission is required to take a profile photo.",
		fromGallery: "Gallery",
		galleryPermissionRequired:
			"Gallery permission is required to select a profile photo.",
		takePhoto: "Take photo",
	},
	settings: {
		about: "About",
		aboutSubtitle:
		"Application information and development credits presented with the same polished card treatment as the rest of the settings workspace.",
		developer: "Developer",
		privacyPolicy: "Privacy Policy",
		privacyPolicyDescription: "Read how we handle your data",
		dailyReportCalculations: "Daily Report Calculations",
		followSystem: "Follow system",
		manageApplicationUsers: "Manage Application Users",
		addApplicationUser: "Add Application User",
		preferences: "Preferences",
		quickToggle: "Quick toggle",
		title: "Settings",
		version: "Version",
		workspaceSettings: "Workspace settings",
		settingsAndPreferences: "Settings & Preferences",
		heroSubtitle:
		"Configure application preferences, manage admin-only application users, and keep the experience aligned with your workflow.",
		preferencesPanel: {
			darkModeBody:
				"Choose a manual theme or let the app follow system preferences across the full experience.",
			darkModeTitle: "Dark Mode",
			followDeviceLanguage: "Use device language",
			languageManualBody: "Choose the language you want to keep in the app.",
			languageSystemBody:
				"The app follows your device language. Current language: %{language}.",
			languageTitle: "Application language",
			notifications: "Notifications (%{count})",
			system: "System",
			light: "Light",
			dark: "Dark",
			english: "English",
			spanish: "Spanish",
			followSystemTheme: "Use device theme",
			themeManualBody: "Choose the theme you want to keep in the app.",
			themeSystemBody:
				"The app follows your device theme. Current theme: %{theme}.",
		},
		alerts: {
			applicationUserCreated: "Application user %{id} created successfully.",
			applicationUserDeleted: "Application user %{id} removed successfully.",
			applicationUserUpdated: "Application user %{id} updated successfully.",
			confirmDeleteUser: "Remove %{id}?",
			dailyReportReset: "Daily report calculations were reset to defaults.",
			dailyReportSaved: "Daily report calculations updated successfully.",
			deleteFailed: "Delete failed",
			nextIdFailed: "Could not get the next barber ID.",
			noApplicationUserSelected: "No application user selected.",
			noApplicationUserSearchResult: "No application user found for that search.",
			reportValidation: "Please review the daily report calculation values.",
			saveFailed: "Save failed",
			searchFailed: "Search failed",
			searchHint: "Enter a Barber ID, email, or phone to search.",
			validation: "Please fix the required fields.",
		},
		manageUsersForm: {
			address: "Address",
			accessSection: "Access information",
			barberId: "Barber ID",
			barberName: "Barber full name *",
			barberPhone: "Barber phone *",
			barberProfileSection: "Barber profile",
			barberShopSection: "Barbershop information",
			cameraPermissionRequired:
				"Camera permission is required to take a profile photo.",
			createSubtitle:
				"Use the auto-generated ID and complete all sections to register a new barber in the app.",
			createUser: "Create user",
			editSubtitle:
				"You are editing barber details and access credentials.",
			email: "Email *",
			eyebrow: "Admin tools",
			galleryPermissionRequired:
				"Gallery permission is required to select a profile photo.",
			password: "Password *",
			photoTitle: "Profile photo",
			searchLabel: "Search by Barber ID, email, or phone",
			shopName: "Barbershop name *",
			shopPhone: "Barbershop phone *",
			subtitle:
				"Create, search, update, and remove barbers with a friendlier sectioned form.",
			takePhoto: "Take photo",
			title: "Manage Application Users",
			uploadPhoto: "Upload from gallery",
			updateUser: "Update user",
			userDataTitle: "Application user form",
			username: "Username *",
		},
		reportCalculationForm: {
			commissionPercentage: "Barber commission percentage",
			fixedDailyExpense: "Fixed daily expense",
			subtitle:
				"Net profit is calculated as gross revenue minus barber commission and fixed daily expense.",
			title: "Daily closeout formula",
		},
	},
	validation: {
		appointmentClientNameRequired: "Client name is required.",
		appointmentPaymentMethodRequired: "Select a payment method.",
		appointmentServicePricePositive: "Price must be greater than 0.",
		appointmentServicePriceRequired: "Service price is required.",
		appointmentTimeRequired: "Time is required.",
		addressRequired: "Address is required.",
		barberNameRequired: "Barber name is required.",
		barberPhoneFormat: "Barber phone must be 0000-0000.",
		barberPhoneRequired: "Barber phone is required.",
		commissionPercentageRange: "Commission percentage must be between 0 and 100.",
		emailRequired: "Email is required.",
		error: "An unexpected error occurred.",
		fixedDailyExpenseRange: "Fixed daily expense must be 0 or greater.",
		invalidEmail: "Invalid email address.",
		lastNameRequired: "Last name is required.",
		nameRequired: "Name is required.",
		passwordLength: "Password must have at least 6 characters.",
		passwordRequired: "Password is required.",
		passwordsMustMatch: "Passwords do not match.",
		phoneFormat: "Phone must be 0000-0000.",
		phoneRequired: "Phone is required.",
		required: "Required.",
		shopNameRequired: "Barbershop name is required.",
		shopPhoneFormat: "Barbershop phone must be 0000-0000.",
		shopPhoneRequired: "Barbershop phone is required.",
		usernameRequired: "Username is required.",
	},
	appointments: {
		paymentMethods: {
			card: "Credit/Debit Card",
			cash: "Cash",
			sinpeMovil: "Sinpe Movil",
			transfer: "Digital Transfer",
		},
		alerts: {
			appointmentAlertTitle: "Edit Appointment",
			noCompletedIfNotConfirmed: "Only confirmed appointments can be completed.",
			noCancelledIfCompleted: "Cannot cancel an appointment if it is completed.",
			noConfirmedIfCompleted: "Cannot confirm an appointment if it is completed.",
			noScheduledIfCancelled: "Cannot schedule a cancelled appointment.",
			areYouSureCancelAppointment: "Are you sure you want to cancel the appointment?",
			hoursUntilAppointmentIsConfirmed: "An appointment can only be confirmed 24 hours in advance.",
			yesAlertResponse: "Yes",
			noAlertResponse: "No",
			moveAppointmentDialogTitle: "Move Appointment",
			noMoveAppointmentConfirmation: "Cannot move a completed or cancelled appointment, only Scheduled or Confirmed appointments.",
			areYouSureMoveAppointment: "You are about to move the appointment, are you sure you want to proceed?",
			reassignDateTimeAppointment: "Reassign date and time",
			moveThisAppointmentToOtherSchedule: "Move this appointment to another day or time.",
			moveAppointmentCta: "Move appointment",
		},
	},
	otp: {
		title: "Verify your account",
		subtitle: "We've sent a 6-digit code to",
		invalidCode: "The code entered is incorrect or has expired.",
		noCode: "Didn't receive the code?",
		resendIn: "Resend in",
		resendNow: "Resend code now",
	},
	forgotPassword: {
		title: "Forgot your password?",
		subtitle: "Enter your email address and we'll send you a code to reset it.",
		sendCode: "Send code",
		backToLogin: "Back to login",
	},
	resetPassword: {
		title: "New password",
		subtitle: "Create a secure password for your account.",
		newPassword: "New password",
		confirmPassword: "Confirm password",
		savePassword: "Save and log in",
		success: "Password successfully updated",
	},
	clients: {
		alerts: {
			clientCreated: "Client created.",
			clientRemoved: "Client removed successfully.",
			clientUpdated: "Client updated.",
			listLoadFailed: "Clients could not be loaded.",
			noClientSelected: "No client selected to remove.",
			removeClientMessage: "Remove client?",
			removeFailed: "Remove failed",
			saveFailed: "Save failed",
			searchFailed: "Search failed",
			validation: "Please fix the required fields.",
		},
		buttons: {
			createClient: "Create client",
			delete: "Delete",
			findClient: "Find client",
			newClient: "New client",
			scheduleAppointment: "Schedule appointment",
			scheduleAppointmentA11y: "Schedule appointment for %{clientName}",
			resetForm: "Reset form",
			saveChanges: "Save changes",
		},
		list: {
			emptyBody: "Create your first client or refine your search to see matching records here.",
			emptyTitle: "No clients to show",
			helper: "Tap any client to update the information already registered in the system.",
			listTitle: "Client directory",
			nextPage: "Next page",
			noEmail: "No email registered",
			page: "Page %{current} of %{total}",
			pageSize: "Per page:",
			prevPage: "Previous page",
			searchPlaceholder: "Search by name, phone, or email",
			subtitle: "Review clients, open a record to edit it, or create a new one from the floating action menu.",
			title: "Clients workspace",
			totalCount: "%{count} clients",
		},
		form: {
			activeDescription: "Use this to show whether the client profile is currently active.",
			activeTitle: "Client active",
			address: "Address",
			birthday: "Birthday",
			createEyebrow: "Create client",
			createScreenTitle: "Create client",
			createTitleFallback: "New client",
			createSubtitle: "Add contact details and preferences to save this client.",
			editEyebrow: "Client profile",
			editScreenTitle: "Edit client",
			editingExisting: "Editing existing client",
			email: "Email",
			firstName: "First name *",
			identitySubtitle: "Required information to create or update a client profile.",
			identityTitle: "Identity",
			lastName: "Last name *",
			paymentMethod: "Payment method",
			phone: "Phone *",
			preferences: "Preferences",
			preferencesSubtitle: "Set payment preferences and active status.",
			preferencesTitle: "Preferences",
			profileDetailsSubtitle: "Optional information that helps personalize the experience.",
			profileDetailsTitle: "Profile details",
			selectDate: "Select date",
			statusActive: "Active",
			statusInactive: "Inactive",
			contactTitle: "Contact",
			contactSubtitle: "Reach out directly to this client.",
			callButton: "Call",
			messageButton: "Message",
		},
		paymentMethods: {
			cash: "Cash",
			none: "None",
			sinpeMovil: "Quick Transfer (Sinpe)",
			transfer: "Bank Transfer",
		},
		screen: {
			existingClientBody:
				"Update contact details, preferences, and account status for the selected client.",
			heroEyebrow: "Client workspace",
			newClientBody:
				"Create a polished client profile with contact details, preferences, and account status.",
			noClientSelectedTitle: "Client management",
			title: "Clients",
		},
		searchModal: {
			emptyBody:
				"Use the search field to find existing clients without loading the full directory.",
			emptyTitle: "No clients found",
			eyebrow: "Find client",
			message: "Message",
			placeholder: "Search clients",
			select: "Select",
			subtitle: "Search by name, phone, or any available client detail.",
			title: "Search saved clients",
		},
	},
	dailyReport: {
		attendanceEyebrow: "Attendance",
		attendanceSubtitle: "Detailed ledger of the completed clients counted in this closure.",
		attendanceTitle: "Completed appointments",
		changeDay: "Change day",
		collectionsEyebrow: "Collections",
		collectionsSubtitle:
		"Review how the day's completed sales were paid to reconcile the cash drawer and digital collections.",
		collectionsTitle: "Payment method breakdown",
		commission: "Commission",
		commissionAmount: "Commission amount",
		completedAppointmentMeta_one: "%{count} completed appointment",
		completedAppointmentMeta_other: "%{count} completed appointments",
		dailyExpense: "Daily expense",
		dailyExpenseBreakdown: "Fixed daily expense",
		formulaEyebrow: "Profit formula",
		formulaSubtitle: "Net profit = gross revenue - barber commission - fixed daily expense",
		formulaTitle: "Daily earnings",
		generalService: "General service",
		heroEyebrow: "Shop owner summary",
		heroSubtitle:
		"Track completed services, collected sales, and actual daily profit from one operational report.",
		heroTitle: "Daily closure report",
		metrics: {
			customersServed: "Customers served",
			grossRevenue: "Gross revenue",
			netProfit: "Net profit",
		},
		noCompletedAppointments: "No completed appointments",
		noCompletedAppointmentsBody:
		"Mark appointments as completed in Calendar to include them in the daily closure report.",
		paymentMethodNotSet: "Payment method not set",
		selectedDay: "Selected day",
		title: "Daily Closure",
	},
	calendar: {
		agendaDay: "Day agenda",
		appointmentCountForDay_one: "%{count} appointment for this day",
		appointmentCountForDay_other: "%{count} appointments for this day",
		emptyBodyDay: "No appointments have been booked for this day yet.",
		emptyBodyMonth:
		"Select a day in the calendar to view appointments or long-press it to create a new booking.",
		emptyBodyWeek: "Select a day of the week and use Schedule to create an appointment.",
		emptyTitle: "No appointments",
		hint: "Tap a day to view appointments. Long press to create a new appointment.",
		monthView: "Month view",
		newAppointment: "New appointment",
		schedule: "Schedule",
		selectedDate: "Selected date",
		title: "Calendar",
		today: "Today",
		viewDay: "Day view",
		viewWeek: "Week view",
		weekOf: "Week of %{date}",
		weekSummary_one: "%{count} appointment",
		weekSummary_other: "%{count} appointments",
		appointmentModal: {
			cancel: "Cancel",
			clientName: "Client name",
			completedInfo: "Completed appointments will appear in the daily report.",
			dateSelected: "Selected date: %{date}",
			editTitle: "Edit booking",
			eyebrow: "New appointment",
			notes: "Notes",
			notesPlaceholder: "Instructions, preferences, or reminders",
			paymentMethod: "Payment method",
			paymentMethodPlaceholder: "Select how this appointment was charged",
			phone: "Phone",
			saveAppointment: "Save appointment",
			saveChanges: "Save changes",
			service: "Service",
			servicePlaceholder: "Classic haircut, beard trim, combo...",
			servicePrice: "Service price",
			status: "Appointment status",
			statuses: {
				cancelled: "Cancelled",
				completed: "Completed",
				confirmed: "Confirmed",
				scheduled: "Scheduled",
			},
			time: "Time",
			title: "Schedule appointment",
		},
	},
	main: {
		welcome: "Welcome, %{name}",
		newAppointment: "New appointment",
		today: "Today's agenda",
	},
	notifications: {
		alerts: {
			refreshFailed: "Notifications could not be refreshed.",
			refreshFailedTitle: "Refresh failed",
		},
		delayedClientsDescription:
		"Clients who have not visited recently and do not have a future appointment.",
		delayedClientsEmptyBody:
		"Delayed-client reminders will appear here once a client crosses the current follow-up threshold.",
		delayedClientMessage: "%{name} has not visited in %{days} days.",
		delayedClientsEmptyTitle: "No delayed clients",
		delayedClientsTitle: "Needs Attention",
		disabledBody: "Enable notifications in Settings to restore the summary feed and unread badge counts.",
		disabledTitle: "Notifications are disabled",
		heroEyebrow: "Daily summary",
		heroSubtitle:
		"Review tomorrow's agenda, identify clients that need follow-up, and keep notification noise reduced to actionable summaries.",
		heroTitle: "Notifications workspace",
		metaNeedsFollowUp: "Needs follow-up",
		metaTomorrow: "Tomorrow",
		tomorrowDescription: "One summary notification for tomorrow's scheduled appointments.",
		tomorrowEmptyBody:
		"When appointments exist for tomorrow, the app will group them into a single daily agenda summary.",
		tomorrowEmptyTitle: "No summary for tomorrow",
		tomorrowMessageOne: "You have 1 appointment scheduled for tomorrow with %{name}.",
		tomorrowMessageOther: "You have %{count} appointments scheduled for tomorrow.",
		tomorrowTitle: "Tomorrow",
		title: "Notifications",
	},
	contactActions: {
		callUnavailableMessage: "This client does not have a valid phone number.",
		callUnavailableOpen: "Your device could not open the phone dialer.",
		callUnavailableTitle: "Call unavailable",
		cancel: "Cancel",
		chooseContactMethod: "Choose how to contact this client.",
		sendMessage: "Send message",
		smsLabel: "Text message",
		smsUnavailableMessage: "This client does not have a valid phone number.",
		smsUnavailableOpen: "Your device could not open the SMS app.",
		smsUnavailableTitle: "SMS unavailable",
		whatsappLabel: "WhatsApp",
		whatsappUnavailableMessage: "This client does not have a valid phone number.",
		whatsappUnavailableOpen:
		"WhatsApp is not installed or could not be opened on this device.",
		whatsappUnavailableTitle: "WhatsApp unavailable",
		hello: "Hello",
		helloName: "Hello %{name}",
	},
	barberShops: {
		title: "Barber Shops",
		subtitle: "Manage your barber shop locations",
		noShopsTitle: "No barber shops",
		noShopsBody: "Create your first barber shop to start managing appointments and clients.",
		createShop: "Create barber shop",
		editShop: "Edit barber shop",
		deleteShop: "Delete barber shop",
		shopName: "Shop name *",
		shopPhone: "Shop phone *",
		shopAddress: "Shop address *",
		selectShop: "Select shop",
		currentShop: "Current shop",
		alerts: {
			shopCreated: "Barber shop created successfully.",
			shopUpdated: "Barber shop updated successfully.",
			shopDeleted: "Barber shop deleted successfully.",
			confirmDelete: "Delete this barber shop?",
			validation: "Please fix the required fields.",
			saveFailed: "Failed to save barber shop.",
			deleteFailed: "Failed to delete barber shop.",
		},
	},
	clientHistory: {
		title: "Appointment History",
		noHistory: "No appointment history",
		noHistoryBody: "This client has no completed appointments yet.",
		loadingHistory: "Loading history...",
		loadingStats: "Loading stats...",
		statsTitle: "Client Statistics",
		totalSpent: "Total spent",
		totalAppointments: "Total appointments",
		completionRate: "Completion rate",
		preferredPayment: "Preferred payment",
		lastVisit: "Last visit",
		searchByPhone: "Search by phone",
		searchPlaceholder: "Enter phone number",
		selectClient: "Select client",
		createNewClient: "Create new client",
		useThisClient: "Use this client",
		existingClient: "Existing client found",
		previousAppointments: "Previous appointments",
		modal: {
			title: "Link Client",
			subtitle: "Search for existing client or create new one",
			noResults: "No client found with this phone number",
			noResultsBody: "You can create a new client with this information.",
			skip: "Skip",
			phoneRequired: "Please enter a phone number",
			searchFailed: "Failed to search for client",
		},
	},
	} as const;