	export const es = {
	common: {
		active: "Activo",
		call: "Llamar",
		cancel: "Cancelar",
		close: "Cerrar",
		create: "Crear",
		delete: "Eliminar",
		dismiss: "Descartar",
		inactive: "Inactivo",
		markAllAsRead: "Marcar todo como leído",
		message: "Mensaje",
		ok: "OK",
		open: "Abrir",
		refresh: "Actualizar",
		reset: "Restablecer",
		save: "Guardar",
		search: "Buscar",
		select: "Seleccionar",
		today: "Hoy",
		update: "Actualizar",
		visible: "Visibles",
		unread: "No leídas",
		somethingWentWrong: "Algo salió mal.",
	},
	drawer: {
		cancel: "Cancelar",
		deleteAccount: "Eliminar mi cuenta",
		deleteAccountConfirm: "Eliminar",
		deleteAccountDescription: "Elimina permanentemente tu cuenta y datos",
		deleteAccountMessage: "Esta acción es permanente e irreversible. Se eliminarán todos tus datos.",
		deleteAccountTitle: "Eliminar cuenta",
		help: "Ayuda",
		helpDescription: "Obtén ayuda y guía de uso",
		helpMessage: "Para obtener ayuda, contacta con soporte o revisa la documentación.",
		helpTitle: "Ayuda",
		heroBody:
		"Usa el menú lateral para ir a ajustes, soporte y acciones de cuenta desde una sola superficie de trabajo.",
		logout: "Cerrar sesión",
		logoutDescription: "Cierra la sesión actual en este dispositivo",
		logoutMessage: "¿Seguro que deseas cerrar sesión?",
		logoutTitle: "Cerrar sesión",
		noAccountMetadata: "No hay metadatos de cuenta disponibles",
		settings: "Ajustes",
		settingsDescription: "Tema, idioma, notificaciones y preferencias de la app",
		studioAccess: "Acceso al estudio",
		support: "Soporte",
		workspace: "Espacio de trabajo",
	},
	header: {
		guest: "Invitado",
		openMenu: "Abrir menú",
		openNotifications: "Abrir notificaciones",
		signedInAs: "Sesión iniciada como %{identity}",
		workspace: "Espacio de trabajo",
	},
	login: {
		appointments: "Citas",
		authFailed: "Autenticación fallida",
		clients: "Clientes",
		enterPassword: "Ingresa tu contraseña",
		enterUsername: "Ingresa tu usuario",
		helperText: "Tu sesión se almacena de forma segura en este dispositivo después de iniciar sesión correctamente.",
		heroBody:
		"Inicia sesión para acceder a citas, fichas de clientes, notificaciones y ajustes operativos desde un único espacio profesional.",
		heroTitle: "Gestiona tu barbería con confianza.",
		notifications: "Notificaciones",
		password: "Contraseña",
		secureAccess: "Acceso seguro",
		signIn: "Ingresar",
		signInToContinue: "Ingresa para continuar",
		subtitle: "Usa tu usuario y contraseña asignados para abrir el espacio móvil.",
		username: "Usuario",
		validation: "Ingresa el usuario y la contraseña.",
		welcomeBack: "Bienvenido de nuevo",
	},
	navigation: {
		alerts: "Alertas",
		barberShops: "Barberías",
		calendar: "Agenda",
		clients: "Clientes",
		dailyReport: "Cierre",
		home: "Inicio",
		settings: "Ajustes",
	},
	avatarPicker: {
		cameraPermissionRequired:
			"Se requiere permiso de cámara para tomar una foto de perfil.",
		fromGallery: "Galería",
		galleryPermissionRequired:
			"Se requiere permiso de galería para seleccionar una foto de perfil.",
		takePhoto: "Tomar foto",
	},
	settings: {
		privacyPolicy: "Política de privacidad",
		privacyPolicyDescription: "Lee cómo manejamos tus datos",
		about: "Acerca de",
		aboutSubtitle:
		"Información de la aplicación y créditos de desarrollo presentados con el mismo tratamiento visual del resto del espacio de ajustes.",
		developer: "Desarrollador",
		dailyReportCalculations: "Cálculos de cierre diario",
		followSystem: "Seguir sistema",
		heroSubtitle:
		"Configura las preferencias de la aplicación, administra usuarios de aplicación solo para administradores y mantén la experiencia alineada con tu flujo de trabajo.",
		manageApplicationUsers: "Administrar usuarios de la aplicación",
		addApplicationUser: "Agregar Usuario de Aplicación",
		preferences: "Preferencias",
		quickToggle: "Cambio rápido",
		settingsAndPreferences: "Ajustes y preferencias",
		title: "Ajustes",
		version: "Versión",
		workspaceSettings: "Ajustes del espacio",
		preferencesPanel: {
			darkModeBody:
				"Elige un tema manual o deja que la aplicación siga las preferencias del sistema en toda la experiencia.",
			darkModeTitle: "Modo oscuro",
			dark: "Oscuro",
			english: "Inglés",
			followDeviceLanguage: "Usar idioma del dispositivo",
			followSystemTheme: "Usar tema del dispositivo",
			languageManualBody: "Elige el idioma que deseas mantener en la aplicación.",
			languageSystemBody:
				"La aplicación sigue el idioma del dispositivo. Idioma actual: %{language}.",
			languageTitle: "Idioma de la aplicación",
			light: "Claro",
			notifications: "Notificaciones (%{count})",
			spanish: "Español",
			system: "Sistema",
			themeManualBody: "Elige el tema que deseas mantener en la aplicación.",
			themeSystemBody:
				"La aplicación sigue el tema del dispositivo. Tema actual: %{theme}.",
		},
		alerts: {
			applicationUserCreated: "Usuario de aplicación %{id} creado correctamente.",
			applicationUserDeleted: "Usuario de aplicación %{id} eliminado correctamente.",
			applicationUserUpdated: "Usuario de aplicación %{id} actualizado correctamente.",
			confirmDeleteUser: "¿Eliminar %{id}?",
			dailyReportReset: "Los cálculos del cierre diario se restablecieron a los valores predeterminados.",
			dailyReportSaved: "Los cálculos del cierre diario se actualizaron correctamente.",
			deleteFailed: "No se pudo eliminar",
			nextIdFailed: "No se pudo obtener el siguiente ID de barbero.",
			noApplicationUserSelected: "No hay un usuario de aplicación seleccionado.",
			noApplicationUserSearchResult: "No se encontró un usuario de aplicación para esa búsqueda.",
			reportValidation: "Revisa los valores del cálculo del cierre diario.",
			saveFailed: "No se pudo guardar",
			searchFailed: "No se pudo buscar",
			searchHint: "Ingresa un ID de barbero, correo o teléfono para buscar.",
			validation: "Corrige los campos obligatorios.",
		},
		manageUsersForm: {
			address: "Dirección",
			accessSection: "Información de acceso",
			barberId: "ID del barbero",
			barberName: "Nombre completo del barbero *",
			barberPhone: "Teléfono del barbero *",
			barberProfileSection: "Perfil del barbero",
			barberShopSection: "Información de la barbería",
			cameraPermissionRequired:
				"Se requiere permiso de cámara para tomar una foto del perfil.",
			createSubtitle:
				"Usa el ID autogenerado y completa las secciones para registrar un nuevo barbero en la aplicación.",
			createUser: "Crear usuario",
			editSubtitle:
				"Estás editando la información del barbero y sus datos de acceso.",
			email: "Correo *",
			eyebrow: "Herramientas de administración",
			galleryPermissionRequired:
				"Se requiere permiso de galería para seleccionar una foto de perfil.",
			password: "Contraseña *",
			photoTitle: "Foto de perfil",
			searchLabel: "Buscar por ID de barbero, correo o teléfono",
			shopName: "Nombre de la barbería *",
			shopPhone: "Teléfono de la barbería *",
			subtitle:
				"Crea, busca, actualiza y elimina barberos con un formulario amigable y seccionado.",
			takePhoto: "Tomar foto",
			title: "Administrar usuarios de la aplicación",
			uploadPhoto: "Subir desde galería",
			updateUser: "Actualizar usuario",
			userDataTitle: "Formulario de usuario de aplicación",
			username: "Nombre de usuario *",
		},
		reportCalculationForm: {
			commissionPercentage: "Porcentaje de comisión del barbero",
			fixedDailyExpense: "Gasto fijo diario",
			subtitle:
				"La ganancia neta se calcula como ingresos brutos menos comisión del barbero y gasto fijo diario.",
			title: "Fórmula del cierre diario",
		},
	},
	validation: {
		appointmentClientNameRequired: "El nombre del cliente es obligatorio.",
		appointmentPaymentMethodRequired: "Selecciona un método de pago.",
		appointmentServicePricePositive: "El precio debe ser mayor que 0.",
		appointmentServicePriceRequired: "El precio del servicio es obligatorio.",
		appointmentTimeRequired: "La hora es obligatoria.",
		addressRequired: "La dirección es obligatoria.",
		barberNameRequired: "El nombre del barbero es obligatorio.",
		barberPhoneFormat: "El teléfono del barbero debe tener el formato 0000-0000.",
		barberPhoneRequired: "El teléfono del barbero es obligatorio.",
		commissionPercentageRange: "El porcentaje de comisión debe estar entre 0 y 100.",
		emailRequired: "El correo es obligatorio.",
		error: "Ocurrió un error inesperado.",
		fixedDailyExpenseRange: "El gasto fijo diario debe ser 0 o mayor.",
		invalidEmail: "Correo electrónico no válido.",
		lastNameRequired: "El apellido es obligatorio.",
		nameRequired: "El nombre es obligatorio.",
		passwordLength: "La contraseña debe tener al menos 6 caracteres.",
		passwordRequired: "La contraseña es obligatoria.",
		passwordsMustMatch: "Las contraseñas no coinciden.",
		phoneFormat: "El teléfono debe tener el formato 0000-0000.",
		phoneRequired: "El teléfono es obligatorio.",
		required: "Obligatorio.",
		shopNameRequired: "El nombre de la barbería es obligatorio.",
		shopPhoneFormat: "El teléfono de la barbería debe tener el formato 0000-0000.",
		shopPhoneRequired: "El teléfono de la barbería es obligatorio.",
		usernameRequired: "El nombre de usuario es obligatorio.",
	},
	appointments: {
		paymentMethods: {
			card: "Tarjeta crédito/débito",
			cash: "Efectivo",
			sinpeMovil: "Sinpe Móvil",
			transfer: "Transferencia digital",
		},
		alerts: {
			appointmentAlertTitle: "Editar Reserva",
			noCompletedIfNotConfirmed: "Solo se pueden completar citas confirmadas.",
			noCancelledIfCompleted: "No se puede Cancelar una cita si en estado Completada.",
			noConfirmedIfCompleted: "No se puede Confirmar una cita si en estado Completada.",
			noScheduledIfCancelled: "No se puede Agendar una cita Completada.",
			areYouSureCancelAppointment: "¿Está seguro que desea cancelar la cita?",
			hoursUntilAppointmentIsConfirmed: "",
			yesAlertResponse: "Sí",
			noAlertResponse: "No",
			moveAppointmentDialogTitle: "Mover cita",
			noMoveAppointmentConfirmation: "No se puede mover una cita completada o cancelada, solo citas Programadas o Confirmadas",
			areYouSureMoveAppointment: "¿Usted va a mover la cita, ¿Está seguro de realizar esta acción?",
			reassignDateTimeAppointment: "Reasignar fecha y hora",
			moveThisAppointmentToOtherSchedule: "Mover esta cita a otro día u hora.",
			moveAppointmentCta: "Mover cita",
		},
	},
	otp: {
		title: "Verifica tu cuenta",
		subtitle: "Hemos enviado un código de 6 dígitos a",
		invalidCode: "El código ingresado es incorrecto o ha expirado.",
		noCode: "¿No recibiste el código?",
		resendIn: "Reenviar en",
		resendNow: "Reenviar código ahora",
	},
	forgotPassword: {
		title: "¿Olvidaste tu contraseña?",
		subtitle: "Introduce tu correo electrónico y te enviaremos un código para restablecerla.",
		sendCode: "Enviar código",
		backToLogin: "Volver al inicio",
	},
	resetPassword: {
		title: "Nueva contraseña",
		subtitle: "Crea una contraseña segura para tu cuenta.",
		newPassword: "Nueva contraseña",
		confirmPassword: "Confirmar contraseña",
		savePassword: "Guardar y entrar",
		success: "Contraseña actualizada con éxito",
	},
	clients: {
		alerts: {
			clientCreated: "Cliente creado.",
			clientRemoved: "Cliente eliminado correctamente.",
			clientUpdated: "Cliente actualizado.",
			listLoadFailed: "No se pudieron cargar los clientes.",
			noClientSelected: "No hay un cliente seleccionado para eliminar.",
			removeClientMessage: "¿Eliminar cliente?",
			removeFailed: "No se pudo eliminar",
			saveFailed: "No se pudo guardar",
			searchFailed: "No se pudo buscar",
			validation: "Corrige los campos obligatorios.",
		},
		buttons: {
			createClient: "Crear cliente",
			delete: "Eliminar",
			findClient: "Buscar cliente",
			newClient: "Nuevo cliente",
			scheduleAppointment: "Agendar cita",
			scheduleAppointmentA11y: "Agendar cita para %{clientName}",
			resetForm: "Restablecer formulario",
			saveChanges: "Guardar cambios",
		},
		list: {
			emptyBody: "Crea tu primer cliente o ajusta la búsqueda para ver coincidencias aquí.",
			emptyTitle: "No hay clientes para mostrar",
			helper: "Toca cualquier cliente para actualizar la información registrada en el sistema.",
			listTitle: "Directorio de clientes",
			nextPage: "Página siguiente",
			noEmail: "Sin correo registrado",
			page: "Página %{current} de %{total}",
			pageSize: "Por página:",
			prevPage: "Página anterior",
			searchPlaceholder: "Buscar por nombre, teléfono o correo",
			subtitle: "Revisa clientes, abre un registro para editarlo o crea uno nuevo desde el menú flotante.",
			title: "Espacio de clientes",
			totalCount: "%{count} clientes",
		},
		form: {
			activeDescription: "Úsalo para indicar si el perfil del cliente está activo actualmente.",
			activeTitle: "Cliente activo",
			address: "Dirección",
			birthday: "Cumpleaños",
			createEyebrow: "Crear cliente",
			createScreenTitle: "Crear cliente",
			createTitleFallback: "Nuevo cliente",
			createSubtitle: "Agrega datos de contacto y preferencias para guardar este cliente.",
			editEyebrow: "Perfil del cliente",
			editScreenTitle: "Editar cliente",
			editingExisting: "Editando cliente existente",
			email: "Correo",
			firstName: "Nombre *",
			identitySubtitle: "Información obligatoria para crear o actualizar el perfil del cliente.",
			identityTitle: "Identidad",
			lastName: "Apellido *",
			paymentMethod: "Método de pago",
			phone: "Teléfono *",
			preferences: "Preferencias",
			preferencesSubtitle: "Define preferencias de pago y estado activo.",
			preferencesTitle: "Preferencias",
			profileDetailsSubtitle: "Información opcional que ayuda a personalizar la experiencia.",
			profileDetailsTitle: "Detalles del perfil",
			selectDate: "Seleccionar fecha",
			statusActive: "Activo",
			statusInactive: "Inactivo",
			contactTitle: "Contacto",
			contactSubtitle: "Comunícate directamente con este cliente.",
			callButton: "Llamar",
			messageButton: "Mensaje",
		},
		paymentMethods: {
			cash: "Efectivo",
			none: "Ninguno",
			sinpeMovil: "Sinpe Móvil",
			transfer: "Transferencia",
		},
		screen: {
			existingClientBody:
				"Actualiza los datos de contacto, preferencias y estado de la cuenta del cliente seleccionado.",
			heroEyebrow: "Espacio de clientes",
			newClientBody:
				"Crea un perfil de cliente completo con datos de contacto, preferencias y estado de la cuenta.",
			noClientSelectedTitle: "Gestión de clientes",
			title: "Clientes",
		},
		searchModal: {
			emptyBody:
				"Usa el campo de búsqueda para encontrar clientes existentes sin cargar todo el directorio.",
			emptyTitle: "No se encontraron clientes",
			eyebrow: "Buscar cliente",
			message: "Mensaje",
			placeholder: "Buscar clientes",
			select: "Seleccionar",
			subtitle: "Busca por nombre, teléfono o cualquier detalle disponible del cliente.",
			title: "Buscar clientes guardados",
		},
	},
	dailyReport: {
		attendanceEyebrow: "Asistencia",
		attendanceSubtitle: "Detalle de los clientes completados contados en este cierre.",
		attendanceTitle: "Citas completadas",
		changeDay: "Cambiar día",
		collectionsEyebrow: "Cobros",
		collectionsSubtitle:
		"Revisa cómo se pagaron las ventas completadas del día para conciliar caja y cobros digitales.",
		collectionsTitle: "Desglose por método de pago",
		commission: "Comisión",
		commissionAmount: "Monto de comisión",
		completedAppointmentMeta_one: "%{count} cita completada",
		completedAppointmentMeta_other: "%{count} citas completadas",
		dailyExpense: "Gasto diario",
		dailyExpenseBreakdown: "Gasto fijo diario",
		formulaEyebrow: "Fórmula de ganancia",
		formulaSubtitle: "Ganancia neta = ingresos brutos - comisión del barbero - gasto fijo diario",
		formulaTitle: "Ganancias del día",
		generalService: "Servicio general",
		heroEyebrow: "Resumen del negocio",
		heroSubtitle:
		"Supervisa servicios completados, ventas cobradas y la ganancia real del día desde un solo reporte operativo.",
		heroTitle: "Reporte de cierre diario",
		metrics: {
			customersServed: "Clientes atendidos",
			grossRevenue: "Ingresos brutos",
			netProfit: "Ganancia neta",
		},
		noCompletedAppointments: "No hay citas completadas",
		noCompletedAppointmentsBody:
		"Marca las citas como completadas en Calendario para incluirlas en el reporte de cierre diario.",
		paymentMethodNotSet: "Método de pago no definido",
		selectedDay: "Día seleccionado",
		title: "Cierre diario",
	},
	calendar: {
		agendaDay: "Agenda del día",
		appointmentCountForDay_one: "%{count} cita para este día",
		appointmentCountForDay_other: "%{count} citas para este día",
		emptyBodyDay: "Todavía no hay reservas para este día.",
		emptyBodyMonth:
		"Selecciona un día del calendario para ver sus citas o mantenlo presionado para crear una nueva reserva.",
		emptyBodyWeek: "Selecciona un día de la semana y usa Agendar para crear la cita.",
		emptyTitle: "Sin citas",
		hint: "Toca un día para ver sus citas. Mantén presionado para crear una nueva cita.",
		monthView: "Vista mensual",
		newAppointment: "Nueva cita",
		schedule: "Agendar",
		selectedDate: "Fecha seleccionada",
		title: "Calendario",
		today: "Hoy",
		viewDay: "Vista diaria",
		viewWeek: "Vista semanal",
		weekOf: "Semana de %{date}",
		weekSummary_one: "%{count} cita",
		weekSummary_other: "%{count} citas",
		appointmentModal: {
			cancel: "Cancelar",
			clientName: "Nombre del cliente",
			completedInfo: "Las citas completadas aparecerán en el reporte diario.",
			dateSelected: "Fecha seleccionada: %{date}",
			editTitle: "Editar reserva",
			eyebrow: "Nueva cita",
			notes: "Notas",
			notesPlaceholder: "Indicaciones, preferencias o recordatorios",
			paymentMethod: "Método de pago",
			paymentMethodPlaceholder: "Selecciona cómo se cobró esta cita",
			phone: "Teléfono",
			saveAppointment: "Guardar cita",
			saveChanges: "Guardar cambios",
			service: "Servicio",
			servicePlaceholder: "Corte clásico, barba, combo...",
			servicePrice: "Precio del servicio",
			status: "Estado de la cita",
			statuses: {
				cancelled: "Cancelada",
				completed: "Completada",
				confirmed: "Confirmada",
				scheduled: "Agendada",
			},
			time: "Hora",
			title: "Agendar cita",
		},
	},
	notifications: {
		alerts: {
			refreshFailed: "No se pudieron actualizar las notificaciones.",
			refreshFailedTitle: "Falló la actualización",
		},
		delayedClientsDescription:
		"Clientes que no han visitado recientemente y no tienen una cita futura.",
		delayedClientsEmptyBody:
		"Los recordatorios de clientes atrasados aparecerán aquí cuando un cliente supere el umbral actual de seguimiento.",
		delayedClientMessage: "%{name} no ha visitado en %{days} días.",
		delayedClientsEmptyTitle: "No hay clientes atrasados",
		delayedClientsTitle: "Requieren atención",
		disabledBody: "Activa las notificaciones en Ajustes para restaurar el resumen y el contador de no leídas.",
		disabledTitle: "Las notificaciones están desactivadas",
		heroEyebrow: "Resumen diario",
		heroSubtitle:
		"Revisa la agenda de mañana, identifica clientes que requieren seguimiento y mantén las notificaciones enfocadas en acciones concretas.",
		heroTitle: "Espacio de notificaciones",
		metaNeedsFollowUp: "Requiere seguimiento",
		metaTomorrow: "Mañana",
		tomorrowDescription: "Una notificación de resumen para las citas programadas de mañana.",
		tomorrowEmptyBody:
		"Cuando existan citas para mañana, la app las agrupará en un solo resumen diario de agenda.",
		tomorrowEmptyTitle: "No hay resumen para mañana",
		tomorrowMessageOne: "Tienes 1 cita programada para mañana con %{name}.",
		tomorrowMessageOther: "Tienes %{count} citas programadas para mañana.",
		tomorrowTitle: "Mañana",
		title: "Notificaciones",
	},
	contactActions: {
		callUnavailableMessage: "Este cliente no tiene un número de teléfono válido.",
		callUnavailableOpen: "Tu dispositivo no pudo abrir el marcador telefónico.",
		callUnavailableTitle: "Llamada no disponible",
		cancel: "Cancelar",
		chooseContactMethod: "Elige cómo contactar a este cliente.",
		sendMessage: "Enviar mensaje",
		smsLabel: "Mensaje de texto",
		smsUnavailableMessage: "Este cliente no tiene un número de teléfono válido.",
		smsUnavailableOpen: "Tu dispositivo no pudo abrir la app de SMS.",
		smsUnavailableTitle: "SMS no disponible",
		whatsappLabel: "WhatsApp",
		whatsappUnavailableMessage: "Este cliente no tiene un número de teléfono válido.",
		whatsappUnavailableOpen:
		"WhatsApp no está instalado o no pudo abrirse en este dispositivo.",
		whatsappUnavailableTitle: "WhatsApp no disponible",
		hello: "Hola",
		helloName: "Hola %{name}",
	},
	barberShops: {
		title: "Barberías",
		subtitle: "Administra tus locales de barbería",
		noShopsTitle: "No hay barberías",
		noShopsBody: "Crea tu primera barbería para comenzar a gestionar citas y clientes.",
		createShop: "Crear barbería",
		editShop: "Editar barbería",
		deleteShop: "Eliminar barbería",
		shopName: "Nombre de la barbería *",
		shopPhone: "Teléfono de la barbería *",
		shopAddress: "Dirección de la barbería *",
		selectShop: "Seleccionar barbería",
		currentShop: "Barbería actual",
		alerts: {
			shopCreated: "Barbería creada exitosamente.",
			shopUpdated: "Barbería actualizada exitosamente.",
			shopDeleted: "Barbería eliminada exitosamente.",
			confirmDelete: "¿Eliminar esta barbería?",
			validation: "Por favor corrige los campos requeridos.",
			saveFailed: "Error al guardar la barbería.",
			deleteFailed: "Error al eliminar la barbería.",
		},
	},
	clientHistory: {
		title: "Historial de Citas",
		noHistory: "Sin historial de citas",
		noHistoryBody: "Este cliente aún no tiene citas completadas.",
		loadingHistory: "Cargando historial...",
		loadingStats: "Cargando estadísticas...",
		statsTitle: "Estadísticas del Cliente",
		totalSpent: "Total gastado",
		totalAppointments: "Total de citas",
		completionRate: "Tasa de completitud",
		preferredPayment: "Método de pago preferido",
		lastVisit: "Última visita",
		searchByPhone: "Buscar por teléfono",
		searchPlaceholder: "Ingresa el número de teléfono",
		selectClient: "Seleccionar cliente",
		createNewClient: "Crear nuevo cliente",
		useThisClient: "Usar este cliente",
		existingClient: "Cliente existente encontrado",
		previousAppointments: "Citas previas",
		modal: {
			title: "Vincular Cliente",
			subtitle: "Busca un cliente existente o crea uno nuevo",
			noResults: "No se encontró cliente con este teléfono",
			noResultsBody: "Puedes crear un nuevo cliente con esta información.",
			skip: "Omitir",
			phoneRequired: "Por favor ingresa un número de teléfono",
			searchFailed: "Falló la búsqueda del cliente",
		},
	},
	} as const;